language: julia

os:
    - linux
    - osx

julia:
    - 0.6
    #- nightly

notifications:
    email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

install:
  #- sudo pip install pymdown-extensions

addons:
    apt:
        packages:
            - oracle-java8-installer

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MSTParser"); Pkg.test("MSTParser"; coverage=true)'

after_success:
  #- julia -e 'Pkg.add("Documenter")'
  #- julia -e 'cd(Pkg.dir("MSTParser")); include(joinpath("docs", "make.jl"))'
